# Generated by Django 3.1.3 on 2020-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201107_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
