# Generated by Django 3.1.3 on 2020-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
