# Generated by Django 3.1.3 on 2020-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201108_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=852787356),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
