# Generated by Django 3.1.3 on 2020-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201108_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
