# Generated by Django 3.1.3 on 2020-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201106_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
    ]
