# Generated by Django 3.1.3 on 2020-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201106_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.FloatField(),
        ),
    ]
